// Common memorable words for password generation
export const commonWords = [
  // Short words (2-3 letters)
  'up', 'go', 'do', 'no', 'so', 'on', 'in', 'it', 'if', 'ox',
  'ax', 'my', 'by', 'hi', 'oh', 'we', 'us', 'am', 'an', 'or',
  'act', 'add', 'age', 'ago', 'aid', 'aim', 'air', 'all', 'arm', 'art',
  'ask', 'ate', 'awe', 'ban', 'bar', 'bat', 'bed', 'bet', 'bid', 'bit',
  'bow', 'bud', 'bug', 'bus', 'but', 'buy', 'cab', 'can', 'cap', 'car',
  'cot', 'cow', 'cry', 'cub', 'cur', 'cut', 'dam', 'day', 'den',
  'dew', 'did', 'dig', 'dim', 'dip', 'dot', 'dry', 'dub', 'dud', 'due',
  'dug', 'dye', 'ear', 'eat', 'eel', 'egg', 'ego', 'end', 'era', 'eve',
  'ewe', 'eye', 'fan', 'far', 'fat', 'fax', 'fed', 'fee', 'few', 'fig',
  'fin', 'fit', 'fix', 'flu', 'foe', 'for', 'fry',
  'fun', 'fur', 'gag', 'gap', 'gas', 'gel', 'get', 'gin', 'got',
  'gum', 'gun', 'gut', 'guy', 'gym', 'ham', 'has', 'hat', 'hay',
  'hen', 'her', 'hew', 'hid', 'him', 'hip', 'his', 'hit', 'hog',
  'hop', 'how', 'hub', 'hue', 'hug', 'hut', 'icy',
  'ill', 'ink', 'inn', 'ire', 'irk', 'jab', 'jag',
  'jam', 'jaw', 'jay', 'jig', 'job', 'jog', 'jot',
  'jut', 'keg', 'ken', 'kid', 'kin', 'kit', 'lab', 'lad',
  'lag', 'lap', 'law', 'lay', 'led', 'leg', 'let', 'lid', 'lip', 'lit',
  'log', 'lot', 'low', 'lug', 'mad', 'man', 'map', 'mar', 'mat', 'maw',
  'max', 'may', 'men', 'met', 'mid', 'mix', 'mob', 'mod', 'mop', 'mow',
  'mud', 'nab', 'nag', 'nap', 'net', 'nil', 'nip', 'nit',
  'nod', 'nor', 'not', 'now', 'nun', 'nut', 'oaf', 'oar', 'oat',
  'odd', 'ode', 'off', 'oft', 'ohm', 'oil', 'opt', 'orb',
  'ore', 'our', 'out', 'owe', 'own', 'pad', 'pal', 'pan', 'pap', 'par',
  'pat', 'paw', 'pay', 'pea', 'peg', 'pep', 'per', 'pet', 'pie',
  'pig', 'pin', 'pit', 'ply', 'pod', 'pop', 'pow', 'pry', 'pub',
  'pug', 'pun', 'pup', 'put', 'rag', 'ram', 'ran', 'rap', 'rat',
  'raw', 'ref', 'rev', 'rib', 'rid', 'rig', 'rim', 'rip',
  'rob', 'rod', 'roe', 'rot', 'row', 'rub', 'rum', 'rut',
  'sac', 'sad', 'sag', 'sap', 'sat', 'saw', 'say', 'set',
  'sew', 'shy', 'sin', 'sip', 'sir', 'sis', 'sit', 'six', 'ski',
  'sly', 'sob', 'sod', 'son', 'sop', 'sot', 'sow', 'soy', 'spa', 'spy',
  'sty', 'sub', 'sue', 'sum', 'sup', 'tab', 'tad', 'tag', 'tan',
  'tap', 'tar', 'tax', 'ten', 'thy', 'tic', 'tie',
  'tip', 'toe', 'ton', 'too', 'top', 'tot', 'tow', 'toy', 'try', 'tub',
  'tug', 'two', 'use', 'van', 'vat', 'vet', 'vex', 'via', 'vie',
  'vim', 'wad', 'wag', 'war', 'wax', 'way', 'web', 'wed',
  'wet', 'who', 'why', 'wig', 'win', 'wit', 'woe', 'wok', 'won', 'woo',
  'wow', 'yam', 'yap', 'yaw', 'yea', 'yes', 'yet', 'yin',
  'you', 'zap', 'zig', 'zoo',

  // Animals
  'dog', 'cat', 'bird', 'fish', 'lion', 'bear', 'wolf', 'deer', 'frog', 'duck',
  'horse', 'eagle', 'shark', 'whale', 'tiger', 'snake', 'mouse', 'rabbit', 'fox', 'owl',
  'hawk', 'crow', 'swan', 'goat', 'sheep', 'zebra', 'panda', 'otter', 'seal', 'crab',
  'moth', 'wasp', 'ant', 'bee', 'elk', 'moose', 'bison', 'raven', 'crane', 'heron',
  'turtle', 'lizard', 'parrot', 'falcon', 'dragon', 'monkey', 'donkey', 'camel', 'squid', 'clam',
  'badger', 'jaguar', 'panther', 'viper', 'cobra', 'pelican', 'stork', 'finch', 'wren', 'lark',
  'salmon', 'trout', 'lobster', 'oyster', 'mantis', 'beetle', 'sparrow', 'condor', 'gorilla', 'lemur',
  'alpaca', 'armadillo', 'baboon', 'barracuda', 'buffalo', 'cardinal', 'cheetah', 'chinchilla', 'cicada', 'cockatoo',
  'cougar', 'coyote', 'cricket', 'dolphin', 'dragonfly', 'ferret', 'flamingo', 'gazelle', 'gecko', 'gerbil',
  'gibbon', 'gopher', 'grizzly', 'grouper', 'hamster', 'hedgehog', 'hippo', 'hornet', 'husky', 'hyena',
  'iguana', 'impala', 'jackal', 'jellyfish', 'kangaroo', 'kingfisher', 'koala', 'ladybug', 'leopard', 'llama',
  'lynx', 'macaw', 'mammoth', 'manatee', 'meerkat', 'minnow', 'mongoose', 'narwhal', 'newt', 'ocelot',
  'octopus', 'opossum', 'osprey', 'peacock', 'penguin', 'piranha', 'platypus', 'porcupine', 'python',
  'quail', 'raptor', 'reindeer', 'rooster', 'scorpion', 'seahorse', 'seagull', 'sloth', 'starfish', 'stingray',
  'sturgeon', 'swordfish', 'termite', 'toucan', 'vulture', 'wallaby', 'walrus', 'weasel', 'woodpecker', 'yak',
  'aardvark', 'albatross', 'anaconda', 'anglerfish', 'anteater', 'antelope', 'ape', 'asp', 'bass',
  'beaver', 'blackbird', 'bluebird', 'bluejay', 'boar', 'bobcat', 'bullfinch', 'bullfrog', 'bunny',
  'buzzard', 'caribou', 'catfish', 'chameleon', 'chipmunk', 'cockatiel', 'collie', 'corgi',
  'cormorant', 'crawfish', 'crocodile', 'dingo', 'doberman', 'dove', 'dugong', 'dunlin',
  'emu', 'ermine', 'firefly', 'flounder', 'fowl', 'foxhound', 'gannet', 'garfish',
  'giraffe', 'goldfinch', 'goose', 'grasshopper', 'greyhound', 'grouse', 'gull', 'haddock', 'halibut',
  'hare', 'harrier', 'herring', 'hound', 'hummingbird', 'ibis', 'jackrabbit', 'jay', 'kestrel',
  'kinkajou', 'kite', 'kitten', 'kiwi', 'lamb', 'limpet', 'lionfish', 'locust', 'loon',
  'mackerel', 'magpie', 'mallard', 'mamba', 'marlin', 'marten', 'mastiff', 'meadowlark', 'mockingbird',
  'mole', 'moray', 'mustang', 'nighthawk', 'nightingale', 'oarfish', 'okapi', 'orangutan', 'oriole',
  'parakeet', 'perch', 'pheasant', 'pigeon', 'pike', 'pony', 'poodle',
  'porpoise', 'possum', 'prawn', 'puffin', 'puma', 'puppy', 'quetzal', 'raccoon', 'rattlesnake',
  'retriever', 'rhinoceros', 'roadrunner', 'robin', 'rottweiler', 'sailfish', 'sandpiper', 'sardine', 'sawfish',
  'sheepdog', 'shrew', 'shrimp', 'skunk', 'snail', 'sole', 'spaniel', 'spider',
  'squirrel', 'stallion', 'starling', 'swallow', 'tadpole', 'tapir', 'tern', 'terrier',
  'thrush', 'toad', 'tortoise', 'tuna', 'turkey', 'vole', 'warbler',
  'wombat', 'woodchuck', 'worm', 'yellowjacket', 'zebrafish',

  // Colors
  'red', 'blue', 'green', 'gold', 'pink', 'black', 'white', 'gray',
  'silver', 'bronze', 'coral', 'ivory', 'amber', 'crimson', 'violet', 'indigo',
  'scarlet', 'teal', 'navy', 'maroon', 'olive', 'peach', 'plum', 'rust',
  'cyan', 'khaki', 'beige', 'charcoal', 'cobalt', 'magenta', 'topaz', 'onyx',
  'azure', 'lavender', 'burgundy', 'turquoise', 'mauve', 'ochre', 'sienna', 'umber',
  'vermilion', 'cerulean', 'chartreuse', 'fuchsia', 'periwinkle', 'tangerine', 'saffron', 'sage',
  'champagne', 'mahogany', 'pewter', 'slate', 'taupe', 'lilac', 'mint',
  'apricot', 'aqua', 'auburn', 'blush', 'brick', 'buff', 'carmine', 'cerise',
  'claret', 'copper', 'cream', 'daffodil', 'ebony', 'ecru', 'emerald', 'flax',
  'garnet', 'ginger', 'graphite', 'hazel', 'henna', 'jade', 'jet', 'lemon',
  'lime', 'malachite', 'melon', 'midnight', 'moss', 'mustard', 'opal', 'orchid',
  'pearl', 'pine', 'powder', 'primrose', 'pumpkin', 'ruby', 'russet',
  'sand', 'sapphire', 'sepia', 'smoke', 'steel', 'stone', 'sunset', 'tan',
  'thistle', 'titanium', 'tomato', 'wine', 'wisteria',

  // Nature - Earth
  'tree', 'star', 'moon', 'sun', 'rain', 'snow', 'wind', 'leaf', 'rock',
  'river', 'lake', 'ocean', 'cloud', 'storm', 'flame', 'frost', 'stone', 'sand',
  'cliff', 'cave', 'peak', 'vale', 'marsh', 'brook', 'creek', 'pond', 'reef',
  'grove', 'field', 'meadow', 'forest', 'desert', 'island', 'glacier', 'canyon', 'volcano',
  'thunder', 'lightning', 'breeze', 'tide', 'wave', 'pebble', 'boulder', 'crystal',
  'rapids', 'geyser', 'lagoon', 'ravine', 'thicket', 'swamp', 'dune', 'fjord', 'gorge',
  'waterfall', 'mountain', 'hillside', 'plateau', 'cavern', 'grotto', 'quarry', 'badlands', 'basin',
  'bluff', 'butte', 'delta', 'estuary', 'gully', 'mesa', 'prairie', 'savanna', 'tundra',
  'wetland', 'woodland', 'highland', 'lowland', 'foothill', 'ridgeline', 'shoreline', 'coastline', 'riverbank',
  'snowcap', 'icecap', 'mudflat', 'sandbar', 'bedrock', 'limestone', 'sandstone', 'shale',

  // Food & Drink
  'cake', 'milk', 'bread', 'apple', 'pizza', 'rice', 'corn', 'meat',
  'grape', 'lemon', 'mango', 'berry', 'honey', 'butter', 'cheese', 'bacon',
  'steak', 'pasta', 'toast', 'sugar', 'spice', 'candy', 'cream', 'syrup',
  'salad', 'soup', 'taco', 'curry', 'sushi', 'melon', 'cherry', 'walnut',
  'almond', 'ginger', 'pepper', 'onion', 'garlic', 'cocoa', 'pretzel', 'waffle',
  'nutmeg', 'basil', 'thyme', 'cumin', 'fennel', 'turnip', 'radish', 'celery',
  'avocado', 'banana', 'biscuit', 'brisket', 'brownie', 'burrito', 'caramel', 'cashew',
  'chestnut', 'chowder', 'cinnamon', 'cobbler', 'coconut', 'cookie', 'cracker', 'croissant',
  'custard', 'dumpling', 'espresso', 'falafel', 'fritter', 'granola', 'guava', 'hazelnut',
  'hummus', 'kebab', 'kimchi', 'lasagna', 'lentil', 'macaron', 'muffin', 'noodle',
  'oatmeal', 'olive', 'pancake', 'papaya', 'parsley', 'pecan', 'pickle', 'pineapple',
  'pistachio', 'platter', 'popcorn', 'pudding', 'pumpkin', 'quinoa', 'raisin', 'ravioli',
  'risotto', 'rosemary', 'scallop', 'sesame', 'spinach', 'tamale', 'tempura', 'truffle',
  'vanilla', 'vinegar', 'wasabi', 'yogurt', 'zucchini', 'apricot', 'artichoke', 'baguette',
  'balsamic', 'beet', 'blueberry', 'brioche', 'broccoli', 'cantaloupe', 'cardamom', 'chai',
  'cilantro', 'clementine', 'cranberry', 'cucumber', 'dill', 'edamame', 'eggplant', 'fig',
  'grapefruit', 'jalapeno', 'kale', 'lychee', 'marzipan', 'molasses', 'nectar',
  'oregano', 'paprika', 'pear', 'persimmon', 'pomegranate', 'raspberry', 'sorbet',
  'sourdough', 'strawberry', 'tarragon', 'turmeric', 'watercress', 'wheat', 'yeast',
  'anchovy', 'arugula', 'asparagus', 'barley', 'bourbon', 'butterscotch',
  'cabbage', 'cappuccino', 'cayenne', 'chard', 'chive', 'cider', 'clove',
  'cornbread', 'couscous', 'cupcake', 'danish', 'date', 'donut', 'eclair',
  'endive', 'flaxseed', 'fondant', 'ganache', 'gazpacho', 'gnocchi', 'gouda', 'gratin',
  'grits', 'gyoza', 'horseradish', 'jicama', 'juniper', 'kolache', 'kumquat',
  'leek', 'licorice', 'lime', 'linguine', 'lox', 'macadamia', 'maple', 'meringue',
  'miso', 'mocha', 'muesli', 'mulberry', 'mushroom', 'naan', 'nacho',
  'okra', 'orzo', 'paella', 'panini', 'parmesan', 'parsnip', 'passionfruit',
  'pastry', 'pesto', 'phyllo', 'polenta', 'poppy', 'praline', 'prosciutto', 'ratatouille',
  'relish', 'rhubarb', 'ricotta', 'rye', 'salsa', 'samosa', 'sardine',
  'scone', 'shallot', 'sherbet', 'sorrel', 'squash', 'strudel', 'sumac',
  'tahini', 'tapioca', 'tiramisu', 'toffee', 'tofu', 'torte', 'tortilla',
  'veal', 'venison', 'wafer', 'yam',

  // Actions & Verbs
  'jump', 'run', 'swim', 'fly', 'sing', 'dance', 'laugh', 'smile',
  'climb', 'crawl', 'drift', 'float', 'glide', 'march', 'slide', 'spin',
  'throw', 'catch', 'pull', 'push', 'lift', 'drop', 'kick', 'shout',
  'whisper', 'roar', 'bloom', 'spark', 'flash', 'crash', 'splash', 'twist',
  'fold', 'build', 'carve', 'paint', 'write', 'draw', 'craft', 'soar',
  'dive', 'leap', 'dash', 'bolt', 'charge', 'sprint', 'stride', 'launch',
  'forge', 'grind', 'hoist', 'lunge', 'plunge', 'reach', 'scout', 'steer',
  'weave', 'wield', 'grasp', 'hurdle', 'juggle', 'tumble', 'pivot', 'fling',
  'absorb', 'adapt', 'anchor', 'ascend', 'balance', 'beckon', 'bind', 'blaze',
  'breach', 'breathe', 'burrow', 'capture', 'channel', 'chase', 'claim', 'clench',
  'coil', 'command', 'conjure', 'conquer', 'create', 'crush', 'dart', 'defend',
  'deliver', 'descend', 'devour', 'disarm', 'discover', 'dodge', 'emerge', 'embrace',
  'endure', 'engulf', 'erupt', 'escape', 'evolve', 'expand', 'explore', 'extract',
  'falter', 'feast', 'fetch', 'flicker', 'flourish', 'focus', 'follow', 'fracture',
  'freeze', 'fuse', 'gallop', 'gather', 'generate', 'govern', 'grapple', 'grip',
  'guard', 'guide', 'hack', 'halt', 'harness', 'harvest', 'hasten', 'hatch',
  'hover', 'ignite', 'illuminate', 'immerse', 'impact', 'implode', 'impose', 'infuse',
  'inhabit', 'inject', 'inspire', 'intercept', 'invade', 'invent', 'invoke', 'isolate',
  'jolt', 'kindle', 'kneel', 'latch', 'levitate', 'linger', 'lurk', 'maneuver',
  'mend', 'merge', 'migrate', 'morph', 'navigate', 'nurture', 'observe', 'orbit',
  'overcome', 'patrol', 'penetrate', 'persist', 'pierce', 'plunder', 'ponder', 'propel',
  'protect', 'prowl', 'pursue', 'radiate', 'rally', 'rampage', 'reclaim', 'recoil',
  'reform', 'reign', 'release', 'repel', 'resist', 'restore', 'retreat', 'reveal',
  'revolve', 'ricochet', 'roam', 'rotate', 'rupture', 'salvage', 'scatter', 'scorch',
  'seal', 'seize', 'shatter', 'shelter', 'shift', 'siege', 'signal', 'silence',
  'simmer', 'sketch', 'skim', 'sling', 'smash', 'snare', 'soothe',
  'split', 'sprout', 'stalk', 'stampede', 'startle', 'strike', 'surge', 'sustain',
  'swoop', 'tangle', 'thrive', 'topple', 'trace', 'track', 'transform', 'traverse',
  'trigger', 'triumph', 'uncover', 'unfold', 'unite', 'unleash', 'unlock', 'unravel',
  'uplift', 'vanish', 'venture', 'vibrate', 'wander', 'ward', 'whirl', 'wrestle', 'yield',

  // Objects & Things
  'book', 'desk', 'lamp', 'door', 'key', 'ring', 'box', 'cup', 'pen',
  'bell', 'drum', 'flute', 'horn', 'harp', 'coin', 'gem', 'crown', 'shield',
  'sword', 'arrow', 'blade', 'chain', 'rope', 'wheel', 'clock', 'mirror', 'candle',
  'bridge', 'tower', 'castle', 'cabin', 'fence', 'gate', 'arch', 'pillar', 'throne',
  'hammer', 'anvil', 'chisel', 'needle', 'thread', 'ribbon', 'banner', 'flag', 'kite',
  'anchor', 'compass', 'lantern', 'basket', 'bucket', 'barrel', 'crate', 'vault', 'chest',
  'prism', 'scroll', 'goblet', 'dagger', 'spear', 'quill', 'locket', 'brooch', 'scepter',
  'furnace', 'beacon', 'mortar', 'pestle', 'tripod', 'wrench', 'lever', 'pulley', 'spindle',
  'amulet', 'atlas', 'badge', 'ballast', 'baton', 'bellows', 'binocular', 'blueprint', 'bobbin',
  'brace', 'bracket', 'bridle', 'buckle', 'bugle', 'cable', 'cauldron', 'chalice',
  'cloak', 'cogwheel', 'cradle', 'cylinder', 'decoy', 'emblem', 'engine', 'envelope',
  'faucet', 'feather', 'fiddle', 'flask', 'flywheel', 'fossil', 'funnel', 'gauntlet', 'globe',
  'grille', 'hatchet', 'helmet', 'hourglass', 'ingot', 'javelin', 'keystone', 'knife',
  'knob', 'latch', 'lattice', 'ledger', 'lens', 'lodestone', 'mallet', 'mantle',
  'medallion', 'monocle', 'nozzle', 'oar', 'padlock', 'palette', 'parchment', 'pendant',
  'pickaxe', 'pliers', 'podium', 'propeller', 'quiver', 'ratchet', 'rigging', 'rudder', 'saddle',
  'scaffold', 'scalpel', 'shackle', 'sickle', 'sieve', 'signet', 'sledge', 'socket', 'sundial',
  'tablet', 'talisman', 'telescope', 'template', 'tether', 'timber', 'tinsel', 'torch', 'totem',
  'trebuchet', 'trinket', 'trophy', 'trumpet', 'turntable', 'umbrella', 'wagon', 'whistle',

  // Adjectives & Descriptors
  'big', 'small', 'fast', 'slow', 'hot', 'cold', 'new', 'old', 'soft',
  'hard', 'bright', 'dark', 'loud', 'quiet', 'sharp', 'smooth', 'rough', 'tough',
  'wild', 'calm', 'brave', 'bold', 'keen', 'wise', 'kind', 'fair', 'pure',
  'swift', 'strong', 'proud', 'grand', 'noble', 'vivid', 'fierce', 'gentle', 'humble',
  'lucky', 'happy', 'merry', 'jolly', 'witty', 'clever', 'mighty', 'steady', 'silent',
  'crisp', 'dense', 'agile', 'rapid', 'stark', 'brisk', 'nimble', 'rugged', 'sturdy',
  'golden', 'hollow', 'frozen', 'molten', 'frosty', 'stormy', 'dusty', 'rustic', 'serene',
  'ancient', 'arcane', 'arid', 'astute', 'barren', 'bitter', 'blunt', 'brittle',
  'candid', 'civil', 'coarse', 'cosmic', 'crafty', 'daring', 'dismal', 'divine', 'dreary',
  'earthy', 'elegant', 'elusive', 'epic', 'exotic', 'faint', 'feral', 'fluid', 'frail',
  'frigid', 'gallant', 'gaunt', 'giddy', 'glacial', 'gloomy', 'glossy', 'graceful', 'grim',
  'gruff', 'hardy', 'harsh', 'hasty', 'hearty', 'hefty', 'hushed',
  'immense', 'jagged', 'jovial', 'lively', 'lone', 'lucid', 'lunar',
  'lush', 'lustrous', 'majestic', 'meek', 'mellow', 'misty', 'mortal', 'muted', 'mystic',
  'naive', 'nocturnal', 'opaque', 'ornate', 'pale', 'placid', 'plush',
  'polar', 'potent', 'primal', 'pristine', 'radiant', 'regal', 'rigid', 'robust', 'rosy',
  'rotten', 'royal', 'sacred', 'savage', 'scarce', 'scenic', 'shallow', 'sheer', 'shrewd',
  'sleek', 'slender', 'slight', 'solemn', 'somber', 'sonic', 'sour', 'sparse', 'spectral',
  'spry', 'stale', 'steep', 'stern', 'stiff', 'stoic', 'stout', 'subtle', 'supple',
  'tame', 'tart', 'tender', 'tepid', 'terse', 'thick', 'thorny', 'tidy', 'timid',
  'toxic', 'tranquil', 'turbid', 'uncanny', 'urban', 'utter', 'vacant',
  'vague', 'valiant', 'vast', 'velvet', 'vengeful', 'verdant', 'vibrant', 'vintage', 'vital',
  'volatile', 'wary', 'weary', 'wicked', 'wispy', 'woven', 'wry', 'zealous', 'zesty',

  // Places & Geography
  'north', 'south', 'east', 'west', 'coast', 'shore', 'harbor', 'port', 'bay',
  'ridge', 'summit', 'valley', 'plain', 'delta', 'oasis', 'tundra', 'jungle', 'savanna',
  'mesa', 'bluff', 'atoll', 'steppe', 'plateau', 'inlet', 'hamlet', 'outpost', 'citadel',
  'alcove', 'archipelago', 'bastion', 'borough', 'campsite', 'catacombs', 'crossroads', 'enclave', 'expanse',
  'frontier', 'garrison', 'gateway', 'haven', 'hideout', 'homeland', 'horizon', 'isthmus', 'junction',
  'kingdom', 'labyrinth', 'lagoon', 'landmark', 'lookout', 'mainland', 'outskirts', 'overlook', 'passage',
  'peninsula', 'province', 'realm', 'sanctuary', 'settlement', 'strait', 'territory', 'threshold', 'township',
  'trailhead', 'tributary', 'tropics', 'uplands', 'village', 'vista', 'wasteland', 'wilderness', 'zenith',

  // Time & Seasons
  'dawn', 'dusk', 'noon', 'night', 'spring', 'summer', 'autumn', 'winter', 'epoch',
  'moment', 'decade', 'century', 'sunset', 'sunrise', 'twilight', 'midnight', 'morning',
  'solstice', 'equinox', 'harvest', 'crescent', 'waning', 'eternal', 'fleeting',
  'daybreak', 'nightfall', 'quarter', 'second', 'minute', 'instant', 'interval', 'duration',
  'era', 'eon', 'phase', 'cycle', 'season', 'weekend', 'fortnight', 'millennium', 'eternity',
  'yesterday', 'tomorrow', 'tonight', 'timeless', 'primeval', 'bygone',

  // Materials & Elements
  'iron', 'steel', 'copper', 'brass', 'glass', 'silk', 'wool', 'linen', 'velvet',
  'marble', 'granite', 'jade', 'ruby', 'pearl', 'diamond', 'emerald', 'sapphire', 'opal',
  'nickel', 'chrome', 'titanium', 'quartz', 'obsidian', 'bamboo', 'cedar', 'birch', 'aspen',
  'aluminum', 'beryllium', 'bismuth', 'cadmium', 'calcium', 'carbon', 'gallium',
  'hafnium', 'helium', 'hydrogen', 'iridium', 'krypton', 'lithium', 'manganese', 'mercury',
  'neon', 'niobium', 'nitrogen', 'osmium', 'oxygen', 'palladium', 'phosphorus', 'platinum',
  'plutonium', 'potassium', 'radium', 'rhodium', 'selenium', 'silicon', 'sodium', 'sulfur', 'tantalum',
  'thorium', 'tin', 'tungsten', 'uranium', 'vanadium', 'xenon', 'zinc', 'zirconium',
  'ebony', 'teak', 'rosewood', 'hickory', 'cypress', 'redwood',
  'sandstone', 'limestone', 'basalt', 'pumice', 'chalk', 'clay', 'shale', 'feldspar',
  'ceramic', 'porcelain', 'enamel', 'lacquer', 'resin',

  // Weather & Sky
  'fog', 'mist', 'haze', 'sleet', 'hail', 'blizzard', 'rainbow', 'aurora', 'comet',
  'meteor', 'nebula', 'eclipse', 'zenith', 'orbit', 'cosmos', 'galaxy', 'nova',
  'cirrus', 'nimbus', 'stratus', 'tempest', 'cyclone', 'monsoon', 'tornado', 'flurry', 'squall',
  'drizzle', 'downpour', 'deluge', 'gale', 'gust', 'whirlwind', 'chinook', 'sirocco', 'mistral',
  'typhoon', 'hurricane', 'waterspout', 'sunbeam', 'moonbeam', 'starlight', 'daylight',
  'overcast', 'cumulus', 'thunderhead', 'icicle', 'snowflake', 'raindrop', 'dewdrop', 'sunspot', 'corona',
  'cloudbank', 'fogbank', 'windchill', 'heatwave',

  // Music & Sound
  'chord', 'rhythm', 'melody', 'tempo', 'bass', 'treble', 'hymn', 'chant', 'echo',
  'whistle', 'rumble', 'murmur', 'chime', 'clang', 'buzz', 'hum', 'snap', 'click',
  'ballad', 'sonata', 'fugue', 'riff', 'verse', 'chorus', 'strum', 'pluck', 'tone',
  'anthem', 'aria', 'beat', 'cadence', 'crescendo', 'cymbal', 'discord', 'duet', 'encore',
  'fanfare', 'forte', 'harmony', 'jingle', 'lyric', 'nocturne', 'octave', 'opus', 'overture',
  'percussion', 'pitch', 'prelude', 'quartet', 'refrain', 'requiem', 'resonance', 'serenade', 'solo',
  'soprano', 'symphony', 'tenor', 'timbre', 'trill', 'vibrato', 'waltz', 'acoustic', 'amplify',
  'baritone', 'cello', 'clarinet', 'concerto', 'falsetto', 'harmonica', 'lullaby', 'mandolin',
  'metronome', 'oboe', 'orchestra', 'saxophone', 'staccato', 'tremolo', 'ukulele', 'viola',

  // Body & Movement
  'heart', 'bone', 'fist', 'palm', 'wrist', 'spine', 'skull', 'wing', 'claw',
  'talon', 'tusk', 'mane', 'tail', 'scale', 'shell', 'feather', 'fur', 'antler',
  'sinew', 'tendon', 'muscle', 'marrow', 'breath', 'pulse', 'gait', 'pounce', 'prowl',
  'ankle', 'brow', 'cheek', 'chin', 'elbow', 'finger', 'heel', 'jaw', 'knee',
  'knuckle', 'limb', 'nerve', 'pelvis', 'rib', 'shin', 'shoulder', 'temple', 'thumb',
  'torso', 'vein', 'bicep', 'forearm', 'hamstring', 'ligament', 'sternum',

  // Abstract & Concepts
  'dream', 'hope', 'fate', 'charm', 'spirit', 'quest', 'myth', 'legend', 'saga',
  'glory', 'honor', 'valor', 'grace', 'truth', 'power', 'force', 'logic', 'chaos',
  'riddle', 'puzzle', 'cipher', 'rune', 'sigil', 'token', 'omen', 'vow', 'oath',
  'virtue', 'wisdom', 'enigma', 'paradox', 'karma', 'aura', 'mantra', 'nexus', 'creed',
  'axiom', 'flux', 'ember', 'vigor', 'grit', 'zeal', 'bliss', 'poise', 'ethos',
  'bounty', 'catalyst', 'clarity', 'code', 'conscience', 'covenant',
  'crux', 'decree', 'destiny', 'doctrine', 'dominion', 'edge', 'element',
  'empire', 'endurance', 'essence', 'fable', 'facet', 'faith',
  'fortune', 'freedom', 'fury', 'gambit', 'genesis', 'genius', 'glyph', 'gospel', 'gravity',
  'guardian', 'haven', 'heritage', 'icon', 'ideal', 'impulse', 'infinity',
  'instinct', 'intent', 'justice', 'kinship', 'lament', 'legacy', 'liberty', 'lore', 'majesty',
  'mandate', 'marvel', 'mastery', 'maxim', 'mercy', 'method', 'might', 'miracle', 'mission',
  'momentum', 'motive', 'mystery', 'notion', 'oracle', 'order', 'origin',
  'paradigm', 'paragon', 'passion', 'patron', 'penance', 'pledge', 'ploy',
  'precept', 'prophecy', 'prospect', 'protocol', 'proverb', 'prowess', 'psalm', 'purpose',
  'reason', 'relic', 'remedy', 'resolve', 'rite', 'ritual',
  'rival', 'rogue', 'rubric', 'rumor', 'scheme', 'scope', 'secret', 'sentinel',
  'seraph', 'shadow', 'shrine', 'slogan', 'solace', 'soul',
  'spectrum', 'sphinx', 'stance', 'stigma', 'strategy', 'symbol', 'synergy',
  'tactic', 'theorem', 'thesis', 'treason', 'tribute', 'truce',
  'unity', 'vanguard', 'vendetta', 'verdict', 'vestige', 'vigil', 'vision',
  'vortex', 'warrant', 'will', 'zephyr',

  // Professions & Roles
  'knight', 'king', 'queen', 'prince', 'duke', 'baron', 'lord', 'chief',
  'ranger', 'hunter', 'sailor', 'pilot', 'mason', 'smith', 'baker', 'clerk', 'judge',
  'healer', 'druid', 'wizard', 'mage', 'monk', 'priest', 'sage', 'bard', 'scribe',
  'captain', 'admiral', 'general', 'marshal', 'warden', 'keeper', 'herald', 'squire',
  'archer', 'sentinel', 'paladin', 'nomad', 'hermit', 'mystic', 'alchemist',
  'artisan', 'blacksmith', 'brewer', 'butcher', 'carpenter',
  'champion', 'chancellor', 'chaplain', 'cobbler', 'commander', 'consul', 'corsair', 'courier',
  'craftsman', 'crusader', 'dancer', 'detective', 'diplomat', 'diver', 'doctor', 'earl', 'elder',
  'emperor', 'empress', 'enchanter', 'engineer', 'envoy', 'explorer', 'farmer', 'ferryman',
  'fisherman', 'forester', 'gladiator', 'governor', 'herbalist', 'historian', 'innkeeper', 'inventor', 'jester',
  'jeweler', 'locksmith', 'lumberjack', 'mariner', 'marquis', 'mechanic', 'mercenary', 'merchant', 'midwife',
  'miller', 'miner', 'minister', 'navigator', 'outlaw', 'overseer', 'painter', 'patriarch', 'peasant',
  'philosopher', 'pioneer', 'plumber', 'poet', 'potter', 'preacher', 'prophet', 'rebel',
  'regent', 'scholar', 'sculptor', 'seeker', 'sentry', 'servant', 'sheriff', 'shipwright',
  'soldier', 'sorcerer', 'steward', 'surgeon', 'surveyor', 'tailor', 'templar',
  'thief', 'tracker', 'trader', 'trapper', 'treasurer', 'trooper', 'tycoon', 'vagrant', 'veteran',
  'vicar', 'viking', 'villager', 'vintner', 'viscount', 'voyager', 'wanderer', 'warrior', 'watchman',

  // Tools & Technology
  'gear', 'bolt', 'wire', 'node', 'grid', 'lens', 'dial', 'valve', 'piston',
  'motor', 'radar', 'laser', 'sonar', 'signal', 'circuit', 'switch', 'fuse', 'relay',
  'turbine', 'dynamo', 'magnet', 'sensor', 'probe', 'router', 'cable', 'pixel', 'voxel',
  'codec', 'servo', 'rotor', 'shaft', 'crank', 'gauge', 'meter', 'diode',
  'algorithm', 'antenna', 'aperture', 'battery', 'binary', 'buffer', 'caliber', 'capacitor',
  'centrifuge', 'chassis', 'clutch', 'compiler', 'conduit', 'console', 'converter', 'coolant',
  'coupling', 'database', 'debug', 'decoder', 'device', 'digital', 'display', 'driver',
  'electrode', 'emitter', 'encoder', 'ethernet', 'exhaust', 'filament', 'filter', 'firmware',
  'flywheel', 'framework', 'frequency', 'gasket', 'generator', 'gyroscope', 'hardware', 'inductor', 'interface',
  'inverter', 'kernel', 'keypad', 'kinetic', 'mainframe', 'matrix', 'membrane', 'microchip', 'module',
  'monitor', 'network', 'nucleus', 'optical', 'oscillator', 'output', 'panel', 'particle', 'payload',
  'pipeline', 'platform', 'plugin', 'polymer', 'portal', 'processor', 'protocol', 'quantum', 'reactor',
  'receiver', 'regulator', 'resistor', 'scanner', 'schematic', 'server', 'software', 'solar',
  'terminal', 'thermal', 'throttle', 'transducer', 'transistor', 'transmitter', 'vector', 'voltage',

  // Terrain & Landforms
  'knoll', 'butte', 'ledge', 'crest', 'slope', 'basin', 'trench', 'gully', 'hollow',
  'mound', 'terrace', 'crater', 'caldera', 'cavern', 'grotto',
  'shoal', 'strait', 'channel', 'estuary', 'cove', 'gulf', 'cape', 'isthmus',
  'abyss', 'chasm', 'col', 'couloir', 'crevasse', 'defile',
  'divide', 'escarpment', 'fault', 'fissure', 'floodplain', 'headland', 'hillock',
  'hummock', 'karst', 'moraine', 'outcrop', 'overhang', 'pass', 'pinnacle', 'promontory',
  'scarp', 'spur', 'tableland', 'tor', 'watershed',

  // Plants & Vegetation
  'oak', 'pine', 'elm', 'ash', 'fir', 'yew', 'ivy', 'moss', 'fern',
  'palm', 'maple', 'willow', 'spruce', 'poplar', 'laurel', 'orchid', 'lotus', 'tulip',
  'rose', 'lily', 'daisy', 'iris', 'clover', 'thistle', 'heather', 'jasmine',
  'mint', 'hemp', 'reed', 'vine', 'shrub', 'blossom', 'petal',
  'acorn', 'bark', 'root', 'thorn', 'sprout', 'lichen', 'fungus', 'cactus',
  'alder', 'azalea', 'begonia', 'bluebell', 'bonsai', 'bramble', 'buttercup', 'camellia',
  'carnation', 'chrysanthemum', 'cottonwood', 'crocus', 'dahlia', 'dandelion', 'dogwood',
  'elderberry', 'eucalyptus', 'foxglove', 'gardenia', 'geranium', 'ginkgo', 'goldenrod', 'hawthorn', 'hemlock',
  'hibiscus', 'holly', 'honeysuckle', 'hyacinth', 'hydrangea', 'juniper', 'lilac', 'magnolia',
  'marigold', 'mulberry', 'narcissus', 'nettle', 'oleander', 'pansy', 'peony', 'primrose',
  'ragweed', 'rhododendron', 'sagebrush', 'sassafras', 'sequoia', 'snapdragon', 'sunflower',
  'sycamore', 'tansy', 'verbena', 'wisteria', 'yarrow', 'zinnia',

  // Celestial & Space
  'planet', 'pulsar', 'quasar', 'void', 'rift', 'warp', 'photon',
  'plasma', 'neutron', 'proton', 'stellar', 'astral',
  'nadir', 'apex', 'vertex', 'equator', 'meridian', 'parsec',
  'asteroid', 'blackhole', 'celestial', 'cluster', 'constellation', 'corona',
  'dwarf', 'flare', 'fusion', 'galactic', 'interstellar',
  'jupiter', 'lightyear', 'magnetar', 'mars', 'neptune', 'nova',
  'parallax', 'pluto', 'radiation', 'redshift', 'rocket', 'satellite', 'saturn',
  'singularity', 'skyline', 'spacetime', 'stardust', 'supernova', 'telescope', 'universe', 'venus',

  // Emotions & States
  'joy', 'rage', 'fury', 'pride', 'grief', 'awe', 'love', 'trust',
  'doubt', 'shock', 'thrill', 'dread', 'wonder', 'sorrow', 'delight', 'envy', 'peace',
  'fervor', 'angst', 'elation', 'serenity', 'nostalgia', 'euphoria', 'solace', 'rapture', 'mirth',
  'anguish', 'boredom', 'comfort', 'contempt', 'courage', 'curiosity', 'despair', 'disgust',
  'ecstasy', 'empathy', 'fatigue', 'frenzy', 'frustration', 'gratitude', 'guilt', 'hysteria',
  'jealousy', 'kindness', 'longing', 'malice', 'melancholy', 'nirvana', 'optimism', 'panic',
  'patience', 'pity', 'pleasure', 'regret', 'relief', 'remorse', 'resentment', 'reverence',
  'sadness', 'scorn', 'shame', 'surprise', 'suspense', 'sympathy', 'tension', 'terror', 'torment',
  'tranquility', 'turmoil', 'unease', 'warmth', 'wrath', 'yearning', 'zest',

  // Maritime & Ocean
  'hull', 'mast', 'sail', 'helm', 'keel', 'bow', 'stern', 'deck', 'plank',
  'buoy', 'dock', 'pier', 'wharf', 'jetty', 'barge', 'vessel', 'frigate',
  'galleon', 'schooner', 'dinghy', 'kayak', 'canoe', 'raft', 'fleet', 'armada', 'voyage',
  'current', 'ripple', 'swell', 'surf', 'foam', 'kelp', 'trident',
  'barnacle', 'bilge', 'boatswain', 'bowsprit', 'bulkhead', 'capsize', 'cargo',
  'chart', 'clipper', 'corsair', 'cutter', 'depths', 'dreadnought', 'fathom',
  'figurehead', 'flagship', 'flotsam', 'gangway', 'harpoon', 'jetsam', 'ketch', 'knot', 'leeway',
  'maritime', 'mooring', 'nautical', 'portside', 'rigging', 'rudder', 'seafarer',
  'shipwreck', 'skipper', 'starboard', 'tiller', 'torpedo', 'undertow', 'windward', 'yawl',

  // Architecture & Structures
  'dome', 'spire', 'column', 'ramp', 'stair', 'beam',
  'truss', 'girder', 'rafter', 'lintel', 'niche', 'foyer', 'attic', 'cellar',
  'turret', 'rampart', 'parapet', 'dungeon', 'moat', 'drawbridge', 'chapel', 'shrine',
  'manor', 'villa', 'fortress', 'palace', 'temple', 'pagoda', 'minaret', 'obelisk', 'monument',
  'aqueduct', 'arcade', 'balcony', 'balustrade', 'barbican', 'battlement', 'belfry', 'buttress', 'campanile',
  'cathedral', 'cloister', 'colonnade', 'corridor', 'courtyard', 'cupola', 'dormitory', 'embankment', 'facade',
  'gallery', 'gazebo', 'gutter', 'hallway', 'keep', 'lighthouse', 'loggia',
  'mansion', 'mausoleum', 'monastery', 'nave', 'pantheon', 'pavilion', 'plaza', 'portico',
  'pyramid', 'rotunda', 'sanctuary', 'skylight', 'steeple', 'terrace', 'vestibule',
  'viaduct', 'watchtower', 'windmill',

  // Fabrics & Textiles
  'cloth', 'satin', 'denim', 'tweed', 'lace', 'suede', 'canvas', 'burlap', 'muslin',
  'flannel', 'fleece', 'nylon', 'rayon', 'gauze', 'taffeta', 'organza', 'chiffon', 'chenille',
  'angora', 'brocade', 'calico', 'cambric', 'cashmere', 'corduroy', 'cotton', 'crepe', 'damask',
  'felt', 'gingham', 'gossamer', 'jersey', 'leather', 'lycra', 'mohair', 'moleskin',
  'paisley', 'polyester', 'poplin', 'quilted', 'sateen', 'serge', 'spandex', 'tartan',
  'tulle', 'twill', 'velour', 'voile', 'worsted',

  // Games & Sports
  'pawn', 'rook', 'bishop', 'ace', 'joker', 'bluff', 'trump', 'match',
  'rally', 'hurdle', 'volley', 'tackle', 'score', 'goal',
  'medal', 'title', 'league', 'arena', 'track', 'court', 'pitch',
  'amateur', 'athlete', 'bout', 'bracket', 'brawl', 'challenge', 'chess',
  'clutch', 'coach', 'contest', 'corner', 'defense', 'derby', 'dribble', 'duel',
  'endurance', 'fencing', 'final', 'flanker', 'formation', 'freestyle', 'fumble',
  'halftime', 'handicap', 'header', 'inning', 'knockout', 'marathon', 'offense',
  'overtime', 'penalty', 'playoff', 'podium', 'qualifier', 'quarterfinal', 'racket', 'rebound', 'referee',
  'rematch', 'round', 'scrimmage', 'semifinal', 'shutout', 'slalom', 'sparring',
  'stadium', 'striker', 'sweep', 'timeout', 'tournament', 'tryout', 'umpire', 'underdog', 'varsity',

  // Minerals & Gems
  'agate', 'jasper', 'garnet', 'zircon', 'beryl', 'peridot', 'citrine',
  'aquamarine', 'tourmaline', 'amethyst', 'moonstone', 'sunstone', 'mica', 'pyrite', 'flint',
  'alexandrite', 'aventurine', 'azurite', 'bloodstone', 'calcite', 'carnelian', 'chalcedony',
  'cinnabar', 'fluorite', 'galena', 'hematite', 'howlite', 'kunzite', 'labradorite', 'lapis',
  'malachite', 'moldavite', 'rhodonite', 'sardonyx', 'serpentine', 'spinel',
  'tanzanite', 'turquoise', 'unakite', 'zoisite',

  // Mythology & Folklore
  'phoenix', 'griffin', 'hydra', 'sphinx', 'titan', 'nymph', 'sprite', 'pixie', 'gnome',
  'golem', 'wraith', 'specter', 'phantom', 'banshee', 'valkyrie', 'centaur', 'minotaur', 'chimera',
  'kraken', 'leviathan', 'unicorn', 'pegasus', 'basilisk', 'wyvern', 'gargoyle', 'djinn',
  'amazon', 'archangel', 'behemoth', 'cerberus', 'changeling', 'cyclops', 'demon', 'dryad',
  'enchantress', 'fairy', 'familiar', 'fenrir', 'genie', 'ghost', 'ghoul', 'giant',
  'goblin', 'gorgon', 'harpy', 'ifrit', 'kelpie',
  'lich', 'manticore', 'mermaid', 'ogre', 'ouroboros', 'poltergeist', 'revenant',
  'satyr', 'selkie', 'seraph', 'shade', 'shapeshifter', 'siren', 'sylph',
  'thunderbird', 'troll', 'vampire', 'warlock', 'wendigo', 'werewolf', 'wisp', 'witch', 'yeti', 'zombie',

  // Containers & Vessels
  'flask', 'vial', 'jar', 'jug', 'urn', 'pot', 'bowl', 'mug', 'tankard',
  'chalice', 'pitcher', 'crucible', 'cistern', 'silo', 'bunker', 'depot', 'cache',
  'amphora', 'beaker', 'bin', 'bottle', 'canister', 'carafe', 'cartridge',
  'case', 'casket', 'cask', 'coffer', 'compartment', 'container', 'decanter',
  'hamper', 'hopper', 'hutch', 'keg', 'kettle', 'locker', 'pod',
  'pouch', 'purse', 'receptacle', 'reservoir', 'safe', 'sack', 'satchel', 'scabbard',
  'sheath', 'strongbox', 'tank', 'thermos', 'trough', 'trunk', 'tube', 'vat',

  // Science & Discovery
  'atom', 'cell', 'gene', 'helix', 'spore', 'enzyme', 'isotope',
  'oxide', 'alloy', 'compound', 'formula', 'theory', 'proof', 'theorem',
  'catalyst', 'spectrum', 'wavelength', 'frequency', 'voltage', 'mass', 'density',
  'anode', 'bacteria', 'cathode', 'chromosome', 'combustion', 'condenser', 'conductor',
  'cytoplasm', 'diffusion', 'electron', 'entropy', 'equation', 'erosion', 'evolution',
  'experiment', 'fission', 'friction', 'genome', 'geode', 'hypothesis', 'inertia',
  'lattice', 'magma', 'metabolism', 'mineral', 'mitosis', 'molecule', 'momentum',
  'mutation', 'nutrient', 'organism', 'osmosis', 'pathogen', 'peptide',
  'pressure', 'protein', 'reaction', 'refraction', 'ribosome', 'sediment',
  'seismic', 'stimulus', 'symbiosis', 'synapse', 'synthesis', 'tectonic', 'toxin', 'vaccine',
  'variable', 'velocity', 'viscosity', 'vitamin', 'waveform',

  // Directions & Navigation
  'path', 'trail', 'route', 'course', 'heading', 'bearing', 'waypoint',
  'junction', 'detour', 'shortcut', 'passage', 'gateway', 'portal',
  'altitude', 'azimuth', 'bypass', 'cartography', 'coordinate', 'destination',
  'distance', 'eastward', 'elevation', 'expedition', 'highway', 'latitude', 'longitude',
  'milestone', 'northward', 'orientation', 'pathway', 'pilgrimage', 'radius', 'roadmap',
  'seaward', 'skyward', 'southward', 'trajectory', 'transit', 'trek', 'turnpike', 'westward',

  // Sounds & Noises
  'bang', 'clap', 'crack', 'thud', 'sizzle', 'rattle', 'crunch', 'whir',
  'drone', 'howl', 'shriek', 'growl', 'purr', 'chirp', 'croak', 'rustle', 'clatter',
  'babble', 'blare', 'boom', 'cackle', 'clank', 'crackle', 'creak',
  'fizz', 'flutter', 'groan', 'gurgle', 'hiss', 'jangle', 'knock',
  'muffle', 'patter', 'ping', 'plop', 'pounding', 'screech',
  'shuffle', 'sigh', 'slam', 'slap', 'snore', 'sputter', 'squeak', 'squeal', 'stomp',
  'swoosh', 'tick', 'tinkle', 'toll', 'tremor', 'twang', 'wail', 'whimper',
  'whoosh', 'yelp',

  // Shapes & Patterns
  'circle', 'spiral', 'helix', 'cube', 'sphere', 'cone', 'wedge', 'slab',
  'zigzag', 'mosaic', 'fractal', 'chevron',
  'angle', 'axis', 'band', 'bevel', 'border', 'contour', 'cross',
  'curve', 'cylinder', 'disk', 'dot', 'ellipse', 'facet',
  'groove', 'hexagon', 'hoop', 'loop', 'notch', 'octagon',
  'oval', 'parallel', 'pentagon', 'polygon', 'rectangle',
  'sector', 'segment', 'silhouette', 'slot', 'spoke',
  'square', 'strand', 'swirl', 'symmetry', 'taper', 'tessellation', 'tier', 'triangle',
  'whorl',

  // Verbs of Creation
  'mold', 'sculpt', 'etch', 'engrave', 'stitch', 'knit', 'braid',
  'brew', 'distill', 'refine', 'temper', 'anneal', 'weld', 'solder', 'rivet', 'bond',
  'assemble', 'bake', 'cast', 'compose', 'construct', 'cook', 'cure', 'design',
  'develop', 'draft', 'fabricate', 'fashion', 'ferment', 'form', 'frame',
  'generate', 'glaze', 'hone', 'imprint', 'knead', 'laminate',
  'machine', 'manufacture', 'model', 'originate', 'pattern', 'polish',
  'produce', 'quarry', 'render', 'sew', 'sharpen', 'smelt', 'stamp',
  'synthesize', 'whittle',

  // Landscape Features
  'glade', 'clearing', 'canopy', 'arbor', 'hedge', 'copse', 'dell',
  'fen', 'bog', 'moor', 'heath', 'taiga', 'chaparral',
  'arroyo', 'backwater', 'bayou', 'brushland', 'dale', 'downs', 'flatland',
  'foothills', 'glen', 'grassland', 'gulch', 'lea', 'outcrop',
  'pampas', 'parkland', 'pasture', 'peatland', 'rangeland', 'scrubland',
  'timberline', 'treeline', 'undergrowth', 'veldt',

  // Warfare & Combat
  'armor', 'axe', 'ballista', 'barracks', 'broadsword',
  'buckler', 'bulwark', 'cannon', 'catapult', 'cavalry', 'claymore', 'conquest', 'crossbow', 'crusade',
  'cutlass', 'falchion', 'flail', 'flanking', 'gauntlet',
  'greave', 'halberd', 'infantry', 'joust', 'lance', 'legion', 'longbow', 'mace',
  'musket', 'phalanx', 'plunder', 'rapier', 'regiment', 'sabre',
  'scimitar', 'tactics', 'waraxe', 'warhammer',

  // Domestic & Household
  'apron', 'blanket', 'broom', 'carpet', 'chair', 'chimney', 'closet',
  'couch', 'curtain', 'cushion', 'doorbell', 'doorknob', 'drawer', 'drapes', 'dresser',
  'easel', 'fireplace', 'garden', 'hammock', 'kitchen',
  'ladle', 'ladder', 'mattress', 'oven', 'pantry', 'pillow', 'porch',
  'quilt', 'railing', 'rooftop', 'shelf', 'shutter', 'stool', 'stove', 'table',
  'teapot', 'thimble', 'towel', 'trellis', 'vase', 'wardrobe', 'windowsill',

  // Transportation & Vehicles
  'bicycle', 'blimp', 'boat', 'buggy', 'caboose', 'caravan', 'carriage',
  'chariot', 'cruiser', 'diesel', 'ferry', 'freight', 'glider',
  'gondola', 'helicopter', 'hovercraft', 'hydroplane', 'jeep', 'locomotive', 'monorail',
  'motorcycle', 'paddleboat', 'railcar', 'rickshaw', 'rowboat', 'sailboat', 'scooter',
  'sedan', 'sled', 'sleigh', 'speedboat', 'steamer', 'submarine', 'tanker', 'toboggan',
  'tractor', 'trailer', 'tramway', 'trolley', 'tugboat', 'yacht', 'zeppelin',

  // Astronomy & Constellations
  'andromeda', 'aquarius', 'aries', 'cassiopeia',
  'cepheus', 'draco', 'firmament', 'gemini', 'leo',
  'libra', 'lyra', 'magnitude', 'orion',
  'pisces', 'pleiades', 'polaris', 'scorpio', 'sirius', 'taurus', 'ursa', 'vega', 'virgo',

  // World Cultures & Historical
  'amphitheater', 'bazaar', 'colosseum', 'dynasty', 'folklore',
  'hieroglyph', 'idol', 'mandala',
  'pharaoh', 'pilgrim', 'samurai', 'shaman',
  'sultan', 'tribe',

  // Energy & Forces
  'blast', 'burst', 'clash', 'collide', 'combust', 'detonate', 'discharge',
  'electric', 'energy', 'explode', 'fireball', 'fulcrum', 'kinetic',
  'nuclear', 'recoil', 'shockwave',
  'sonic', 'static', 'thrust', 'torque', 'watt',

  // Numbers & Quantities
  'zero', 'twin', 'triple', 'quad', 'penta', 'seven', 'octal', 'nine',
  'dozen', 'hundred', 'thousand', 'million', 'billion', 'half', 'third',
  'double', 'single', 'pair', 'trio', 'swarm', 'horde', 'myriad',

  // Textures & Surfaces
  'bumpy', 'crinkled', 'feathery', 'flaky', 'fluffy', 'fuzzy', 'gnarled', 'grainy',
  'gritty', 'grooved', 'knotted', 'leathery', 'matted', 'pebbled', 'polished', 'prickly',
  'ridged', 'rippled', 'sandy', 'scaly', 'scored', 'silky', 'slick', 'slimy',
  'spongy', 'sticky', 'stony', 'velvety', 'waxy', 'wiry', 'woolly', 'wrinkled',

  // Light & Vision
  'blaze', 'blind', 'blink', 'dim',
  'fade', 'flare', 'gleam', 'glimmer', 'glint', 'glow',
  'halo', 'highlight', 'infrared', 'luminary', 'luminous', 'luster', 'moonlight',
  'neon', 'optic', 'radiance', 'reflect', 'refract', 'shimmer', 'shine',
  'sparkle', 'spotlight', 'starburst', 'ultraviolet',

  // Water & Liquids
  'cascade', 'drain', 'drip', 'droplet', 'eddy', 'falls', 'flood', 'flow', 'fountain',
  'gush', 'melt', 'overflow', 'pool', 'puddle', 'rill', 'runoff', 'seep',
  'shower', 'slush', 'sprinkle', 'steam', 'stream', 'swirl',
  'tidal', 'torrent', 'trickle', 'vapor', 'well', 'whirlpool',

  // Fire & Heat
  'ablaze', 'bonfire', 'brand', 'burn', 'campfire', 'char', 'cinder', 'coal',
  'embers', 'firebrand', 'firewood', 'heat', 'incandescent',
  'inferno', 'kiln', 'lava', 'matchstick', 'pyre',
  'scald', 'scorch', 'sear', 'slag', 'smolder', 'soot',
  'stoke', 'sunburn', 'tinder', 'volcanic', 'warm', 'wildfire',

  // Ice & Cold
  'arctic', 'avalanche', 'chill', 'floe',
  'frostbite', 'glacial', 'hoarfrost',
  'hypothermia', 'iceberg', 'nippy', 'permafrost', 'shiver',
  'snowdrift', 'snowfall', 'subzero', 'thaw',

  // Wind & Air
  'blow', 'crosswind', 'downdraft', 'draft',
  'headwind', 'norther',
  'tailwind', 'trade', 'turbulence', 'twister',
  'updraft', 'westerly', 'windstorm',

  // Magic & Supernatural
  'bewitch', 'cantrip', 'conjure', 'curse', 'divination', 'elixir', 'enchant', 'ethereal',
  'glamour', 'grimoire', 'hallowed', 'haunted', 'illusion', 'incantation', 'jinx',
  'magic', 'mystical', 'occult', 'potion', 'sorcery',
  'spell', 'summoning', 'supernatural', 'transmute', 'vanishing', 'wand',
  'witchcraft', 'wizardry',

  // Communication & Language
  'accent', 'alphabet', 'ballot', 'chapter', 'chronicle', 'clause', 'codex',
  'dialect', 'diary', 'diction', 'dispatch', 'edict', 'epistle', 'gazette', 'glossary',
  'grammar', 'journal', 'lexicon', 'lingua', 'manuscript', 'memoir', 'message',
  'monograph', 'motto', 'narrative', 'pamphlet', 'parable', 'phrase', 'proclamation', 'prose',
  'quote', 'record', 'report', 'rhetoric', 'script', 'sonnet',
  'speech', 'stanza', 'story', 'syllable', 'syntax', 'tale', 'testament', 'text',
  'tome', 'transcript', 'treatise', 'volume', 'word',

  // Music Instruments
  'accordion', 'bagpipe', 'banjo', 'bassoon', 'bongo', 'bugle', 'clarinet',
  'didgeridoo', 'dulcimer', 'fife', 'glockenspiel', 'guitar', 'keyboard',
  'lute', 'lyre', 'marimba', 'organ', 'piano',
  'piccolo', 'recorder', 'sitar', 'snare', 'tambourine', 'timpani', 'trombone',
  'tuba', 'violin', 'xylophone', 'zither',

  // Power Words
  'absolute', 'alpha', 'blitz', 'colossal', 'defiant',
  'elite', 'extreme', 'firestorm', 'juggernaut',
  'maelstrom', 'mammoth', 'monolith', 'nemesis', 'omega', 'pandemonium',
  'renegade', 'sovereign', 'stampede', 'stealth',
  'tsunami', 'vengeance',

  // Occupational Tools
  'awl', 'caliper', 'clamp', 'drill', 'file', 'grinder', 'hacksaw',
  'jig', 'lathe', 'level', 'plane', 'plumb', 'press', 'punch', 'rasp',
  'ruler', 'sander', 'scissors', 'scraper', 'shears', 'spade', 'tongs', 'vise',

  // Philosophical & Intellectual
  'canon', 'dialectic', 'dogma', 'dualism', 'empiric', 'ethics',
  'fallacy', 'heresy', 'idealism', 'logos', 'metaphor', 'nihilism', 'ontology',
  'premise', 'quandary', 'schism', 'stoicism', 'syllogism', 'tenet',
  'utopia', 'zeitgeist',

  // Medieval & Fantasy
  'battlement', 'catapult', 'enchanted', 'fealty', 'grail', 'heraldry', 'maiden',
  'tapestry', 'tournament', 'treasure', 'vassal',

  // Ocean Life
  'anemone', 'conch', 'cuttlefish', 'krill', 'mussel', 'nautilus', 'plankton', 'urchin',
  'sponge', 'tentacle', 'abalone', 'blowfish', 'clownfish', 'crayfish',
  'guppy', 'hagfish', 'hammerhead', 'lamprey',
  'manta', 'mollusk', 'orca', 'puffer',

  // Everyday Life
  'alarm', 'bench', 'button', 'camera', 'chalk', 'clip',
  'coffee', 'comb', 'counter', 'crayon', 'eraser', 'folder',
  'glove', 'handle', 'jacket', 'laptop', 'lighter', 'magnet', 'marker',
  'napkin', 'notebook', 'paddle', 'pencil', 'phone', 'planner', 'pocket', 'poster',
  'receipt', 'remote', 'sandwich', 'scarf', 'shovel',
  'sleeve', 'speaker', 'stapler', 'sticker', 'string',
  'ticket', 'timer', 'tissue', 'toggle', 'toolbox', 'wallet', 'zipper'
];
